namespace EdifactValidator.Services;

public static class RuleDescriptions
{
    public sealed record RuleDetail(string Detail, string? Example = null);

    public static RuleDetail? Get(string code) =>
        _dict.TryGetValue(code, out var d) ? d : null;

    private static readonly Dictionary<string, RuleDetail> _dict = new()
    {
        // ── Syntax ──────────────────────────────────────────────────────────────
        ["SYN_001"]  = new("UNB-Segment (Interchange-Kopf) fehlt. Jede EDIFACT-Datei beginnt mit UNB.",
                           "UNB+UNOC:3+4012345000000:14+4040051000006:14+260101:1200+123'"),
        ["SYN_002"]  = new("UNZ-Segment (Interchange-Ende) fehlt. Jede EDIFACT-Datei endet mit UNZ.",
                           "UNZ+1+123'"),
        ["SYN_003"]  = new("UNZ DE1 stimmt nicht: Anzahl deklarierter Nachrichten weicht von den tatsächlichen UNH/UNT-Paaren ab.",
                           "UNZ+1+123'  ← DE1 = Anzahl Nachrichten im Interchange"),
        ["SYN_004"]  = new("Nachricht ohne geschlossenes UNH/UNT-Paar. Jede Nachricht muss mit UNH beginnen und UNT enden."),
        ["SYN_005"]  = new("UNT DE2 stimmt nicht mit UNH DE1 überein – beide müssen dieselbe Referenznummer tragen.",
                           "UNH+550246+INVOIC:D:96A:UN:EAN005'\n...\nUNT+47+550246'  ← gleiche Ref."),
        ["SYN_005b"] = new("UNT DE1 stimmt nicht: deklarierte Segmentanzahl weicht von der tatsächlichen ab. Muss alle Segmente von UNH bis UNT (inkl.) zählen.",
                           "UNT+47+550246'  ← 47 = Anzahl Segmente inkl. UNH und UNT"),

        // ── INVOIC ──────────────────────────────────────────────────────────────
        ["PORTA_001"]  = new("GLN des Absenders fehlt im UNB-Segment. Pflichtfeld zur Absender-Identifikation.",
                             "UNB+UNOC:3+4012345000000:14+4040051000006:14+..."),
        ["PORTA_001b"] = new("Die Absender-GLN im UNB muss genau 13 Ziffern lang sein."),
        ["PORTA_002"]  = new("NAD+BY (Käufer) fehlt. Ohne Käufer-GLN kann der Beleg keiner Filiale zugeordnet werden.",
                             "NAD+BY+4040051010012::9++Porta Möbel'"),
        ["PORTA_003"]  = new("NAD+IV (Rechnungsempfänger) fehlt. Pflicht laut Porta IT-Leitfaden §4.",
                             "NAD+IV+4040051010012::9++FuG Handelsgesellschaft'"),
        ["PORTA_004"]  = new("NAD+SU (Rechnungssteller/Lieferant) fehlt. Ohne Lieferant-GLN keine Zuordnung möglich.",
                             "NAD+SU+4012345000000::9++Muster GmbH'"),
        ["PORTA_005"]  = new("Steuernummer fehlt. Nach NAD+SU muss RFF+VA (USt-IdNr.) oder RFF+FC (Steuernr.) folgen.",
                             "RFF+VA:DE123456789'\noder:  RFF+FC:12/345/67890'"),
        ["PORTA_006"]  = new("Belegart muss BGM+380 (Rechnung) sein. Gutschriften (393) und andere Typen werden abgewiesen.",
                             "BGM+380+RECHNR+9'"),
        ["PORTA_007"]  = new("Belegnummer BGM DE2 fehlt. Primäres Schlüsselfeld – ohne Nummer keine Belegverarbeitung.",
                             "BGM+380+R2026-001+9'  ← Belegnummer in DE2"),
        ["PORTA_008"]  = new("Belegdatum DTM+137 fehlt. Format: JJJJMMTT mit Qualifier 102.",
                             "DTM+137:20260101:102'"),
        ["PORTA_009"]  = new("Lieferdatum DTM+35 fehlt. Notwendig für Zuordnung zum Warenzugang.",
                             "DTM+35:20260101:102'"),
        ["PORTA_010"]  = new("Bestell-Nr. RFF+ON fehlt. Wird für die Zuordnung zur Porta-Bestellung benötigt.",
                             "RFF+ON:7332333/9/00'"),
        ["PORTA_011"]  = new("Lieferschein-Nr. RFF+DQ fehlt. Pflichtfeld laut Leitfaden §7e.",
                             "RFF+DQ:LS12345'"),
        ["PORTA_012"]  = new("Lieferschein-Nr. überschreitet 10 Stellen. Porta-System erlaubt maximal 10 Zeichen.",
                             "RFF+DQ:LS12345'  ← max. 10 Zeichen"),
        ["PORTA_013"]  = new("DTM+171 (Lieferscheindatum) muss direkt nach RFF+DQ folgen.",
                             "RFF+DQ:LS12345'\nDTM+171:20260101:102'  ← direkt danach"),
        ["PORTA_014"]  = new("Kunden-Nr. RFF+API fehlt. Angabe empfohlen für kundenseitige Zuordnung im Porta-System.",
                             "RFF+API:K99887'"),
        ["PORTA_015"]  = new("MwSt.-Satz TAX+7+VAT fehlt. Steuersatz in DE5 C3 angeben.",
                             "TAX+7+VAT+++:::19'"),
        ["PORTA_016"]  = new("Währung CUX+2 fehlt. Euro-Rechnungen verwenden CUX+2:EUR:4.",
                             "CUX+2:EUR:4'"),
        ["PORTA_017"]  = new("GTIN (LIN DE3 C1) fehlt an einer Position. 13-stelliger Barcode mit Qualifier EN ist Pflicht.",
                             "LIN+1++4012345678901:EN'"),
        ["PORTA_018"]  = new("IMD-Beschreibung fehlt. Qualifier A (Freitext) mit Artikelbezeichnung ist Pflicht.",
                             "IMD+A++:::Artikelbeschreibung'"),
        ["PORTA_019"]  = new("Liefermenge QTY+47 fehlt an einer Position.",
                             "QTY+47:10:PCE'"),
        ["PORTA_019b"] = new("Liefermenge QTY+47 muss größer als 0 sein."),
        ["PORTA_020"]  = new("Positionsbetrag MOA+203 fehlt. Muss Menge × Netto-Einzelpreis entsprechen.",
                             "MOA+203:119.90'"),
        ["PORTA_020b"] = new("Positionsbetrag MOA+203 darf nicht negativ sein."),
        ["PORTA_021"]  = new("Artikelpreis PRI fehlt an einer Position. Mindestens PRI+AAB (Brutto) ist Pflicht.",
                             "PRI+AAB:11.99:::1:PCE'"),
        ["PORTA_021b"] = new("Preis-Qualifier muss AAB (Bruttoeinzelpreis) sein. AAA allein ist nicht erlaubt.",
                             "PRI+AAB:11.99:::1:PCE'  ← AAB zwingend"),
        ["PORTA_022"]  = new("Abschnittskontrolle UNS+S fehlt. Trennt Positions- von Summensteil.",
                             "UNS+S'"),
        ["PORTA_023"]  = new("Endbetrag MOA+77 fehlt. Gesamtbetrag inkl. MwSt.",
                             "MOA+77:1190.00'"),
        ["PORTA_024"]  = new("Gesamtpositionsbetrag MOA+79 fehlt. Nettosumme aller Positionen.",
                             "MOA+79:1000.00'"),
        ["PORTA_025"]  = new("Steuerpflichtiger Betrag MOA+125 fehlt. Nettobetrag als Bemessungsgrundlage.",
                             "MOA+125:1000.00'"),
        ["PORTA_026"]  = new("MwSt.-Betrag MOA+124 fehlt. Absoluter Steuerbetrag.",
                             "MOA+124:190.00'"),
        ["PORTA_027"]  = new("Endbetrag MOA+77 ist 0 oder negativ. Null-Rechnungen werden abgewiesen."),
        ["PORTA_028"]  = new("Rechnungsdatum (DTM+137) liegt vor dem Lieferdatum (DTM+35) – zeitlich nicht plausibel."),
        ["PORTA_029"]  = new("In ALC-Gruppe fehlt Euro-Betrag MOA+8. Absoluter Rabatt-/Zuschlagsbetrag ist Pflicht.",
                             "ALC+A+++1+DI'\nMOA+8:5.00'  ← Pflicht"),
        ["PORTA_030"]  = new("In ALC-Gruppe fehlt Prozentsatz PCD+3. Rabatt-/Zuschlagsprozentsatz ist Pflicht.",
                             "ALC+A+++1+DI'\nPCD+3:5'  ← 5 %"),
        ["PORTA_031"]  = new("Artikel-ALC vorhanden, aber Gesamtrabattbetrag MOA+131 fehlt.",
                             "MOA+131:10.00'"),

        // ── ORDRSP ──────────────────────────────────────────────────────────────
        ["ORDRSP_001"]  = new("Belegart muss BGM+231 (Auftragsbestätigung) sein.",
                              "BGM+231+AB12345+9'"),
        ["ORDRSP_002"]  = new("AB-Nummer BGM DE2 fehlt. Pflichtfeld für Rückverfolgbarkeit.",
                              "BGM+231+AB12345'  ← AB-Nr. in DE2"),
        ["ORDRSP_003"]  = new("Belegdatum DTM+137 fehlt. Manche Lieferanten verwenden stattdessen DTM+4.",
                              "DTM+137:20260325:102'"),
        ["ORDRSP_004"]  = new("Bestell-Nr. RFF+ON fehlt oder leer. Muss auf die Porta-Bestellnummer verweisen.",
                              "RFF+ON:7332333/9/00'"),
        ["ORDRSP_005"]  = new("Käufer NAD+BY fehlt. GLN des Bestellers ist Pflicht.",
                              "NAD+BY+4040051000006::9'"),
        ["ORDRSP_006"]  = new("Lieferant NAD+SU fehlt. GLN des Lieferanten ist Pflicht.",
                              "NAD+SU+4012345000000::9'"),
        ["ORDRSP_007"]  = new("Warenempfänger NAD+DP fehlt. GLN der Lieferadresse ist Pflicht.",
                              "NAD+DP+4040051000440::9'"),
        ["ORDRSP_008"]  = new("Steuernummer fehlt. RFF+VA (USt-IdNr.) oder RFF+FC (Steuernr.) nach NAD+SU empfohlen.",
                              "RFF+VA:DE123456789'  oder  RFF+FC:12/345/67890'"),
        ["ORDRSP_009"]  = new("MwSt.-Satz TAX+7+VAT fehlt. Einige Lieferanten übermitteln ihn auf Positionsebene.",
                              "TAX+7+VAT+++:::19'"),
        ["ORDRSP_010"]  = new("Währung CUX+2 fehlt.",
                              "CUX+2:EUR:4'"),
        ["ORDRSP_011"]  = new("GTIN fehlt in LIN DE3. Eindeutiger Artikelcode mit Qualifier EN ist Pflicht.",
                              "LIN+1++4012345678901:EN'"),
        ["ORDRSP_012"]  = new("Lieferanten-Artikel-Nr. PIA+SA fehlt an einer Position.",
                              "PIA+1+ART123:SA'"),
        ["ORDRSP_013"]  = new("Artikelbeschreibung IMD fehlt an einer Position.",
                              "IMD+F++:::Artikelbezeichnung'"),
        ["ORDRSP_014"]  = new("Bestätigte Menge QTY+21 fehlt an einer Position.",
                              "QTY+21:5:PCE'"),
        ["ORDRSP_014b"] = new("Bestätigte Menge QTY+21 muss größer als 0 sein."),
        ["ORDRSP_015"]  = new("Bruttopreis PRI+AAB fehlt an einer Position.",
                              "PRI+AAB:11.99:::1:PCE'"),
        ["ORDRSP_016"]  = new("Nettopreis PRI+AAA fehlt. Pflicht laut ORDRSP-Leitfaden 06/2023.",
                              "PRI+AAA:10.08:::1:PCE'"),
        ["ORDRSP_017"]  = new("Positionsbetrag MOA+203 ist negativ. Muss ≥ 0 sein."),
        ["ORDRSP_018"]  = new("Abschnittskontrolle UNS+S fehlt.",
                              "UNS+S'"),
        ["ORDRSP_WARN_001"] = new("Interne Artikel-Nr. PIA+BP fehlt an einer Position. Erleichtert Bestellzuordnung.",
                                   "PIA+1+030316604:BP'"),

        // ── DESADV ──────────────────────────────────────────────────────────────
        ["DESADV_001"]  = new("Belegart muss BGM+351 (Lieferavis) sein.",
                              "BGM+351+LS12345+9'"),
        ["DESADV_002"]  = new("Lieferscheinnummer BGM DE2 fehlt.",
                              "BGM+351+LS12345'"),
        ["DESADV_003"]  = new("Lieferdatum DTM+137 fehlt.",
                              "DTM+137:20260325:102'"),
        ["DESADV_004"]  = new("Käufer NAD+BY fehlt.",
                              "NAD+BY+4040051000006::9'"),
        ["DESADV_005"]  = new("Lieferant NAD+SU fehlt.",
                              "NAD+SU+4012345000000::9'"),
        ["DESADV_006"]  = new("Warenempfänger NAD+DP fehlt.",
                              "NAD+DP+4040051000440::9'"),
        ["DESADV_007"]  = new("Steuernummer fehlt. RFF+VA oder RFF+FC nach NAD+SU erwartet.",
                              "RFF+VA:DE123456789'"),
        ["DESADV_008"]  = new("CPS-Segment (Consignment Packing Sequence) fehlt. Pflicht-Struktur für DESADV.",
                              "CPS+1'"),
        ["DESADV_009"]  = new("PAC-Segment (Package) fehlt. Beschreibt Versandeinheiten.",
                              "PAC+1++201'"),
        ["DESADV_010"]  = new("GTIN in LIN fehlt.",
                              "LIN+1++4012345678901:EN'"),

        // ── Allgemeine Warnungen ─────────────────────────────────────────────────
        ["WARN_001"]  = new("UNB DE11=1 markiert die Datei als Test. Testdateien fließen nicht in die Produktivverarbeitung ein."),
        ["WARN_002"]  = new("Skonto-Segment PAT+22 vorhanden. Skonto wird automatisch abgezogen – darf nicht zusätzlich im EDI-Betrag berücksichtigt werden."),
        ["WARN_003"]  = new("Interne Artikel-Nr. PIA+BP fehlt. Der BP-Code erleichtert die Bestellzuordnung im Porta-System.",
                            "PIA+1+030316604:BP'"),
        ["WARN_004"]  = new("Unbekannter FTX-Textschlüssel. Erlaubt: ST1 (Transporthinweis), ST2 (Verpackungshinweis), ST3 (Warnhinweis)."),
    };
}
